version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user
hooks:
  AfterInstall:
    - location: ./scripts/fix_previleges.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: ./scripts/start_server.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: ./scripts/stop_server.sh
      timeout: 300
      runas: root
