### Basic authorization.

GET http://{{host}}:{{port}}/api/user/login
Authorization: Basic {{username}} {{password}}
Content-Type: application/json

###

GET http://localhost:8080/api/product/preset/1
Accept: application/json



###
